from manimlib import DEFAULT_DOT_RADIUS
#SCALE (1_000_000_000)
MANIM_REAL_SCALE = 100_000_000

#Basics
SUN_RADIUS = 696_340_000
EARTH_RADIUS = 6_378_000
MOON_RADIUS = 1_740_000
MARS_RADIUS = 3_389_000


#Distances
SUN_EARTH_DISTANCE = 150_000_000_000
SUN_MARS_DISTANCE = 227_943_000_000
EARTH_MOON_DISTANCE = 384_400_000

#Visualization Factor
SUN_RADIUS_VISUALIZATION_FACTOR = 1
EARTH_RADIUS_VISUALIZATION_FACTOR = 1
MOON_RADIUS_VISUALIZATION_FACTOR = 1

SUN_EARTH_DISTANCE_VISUALIZATION_FACTOR = 1
EARTH_MOON_DISTANCE_VISUALIZATION_FACTOR = 1

#Render Distance
RENDER_SUN_RADIUS = SUN_RADIUS / MANIM_REAL_SCALE * SUN_RADIUS_VISUALIZATION_FACTOR
RENDER_EARTH_RADIUS = EARTH_RADIUS / MANIM_REAL_SCALE * EARTH_RADIUS_VISUALIZATION_FACTOR
RENDER_MOON_RADIUS = MOON_RADIUS / MANIM_REAL_SCALE * MOON_RADIUS_VISUALIZATION_FACTOR
RENDER_MARS_RADIUS = MARS_RADIUS / MANIM_REAL_SCALE 

RENDER_SUN_EARTH_DISTANCE = SUN_EARTH_DISTANCE / MANIM_REAL_SCALE * SUN_EARTH_DISTANCE_VISUALIZATION_FACTOR
RENDER_EARTH_MOON_DISTANCE = EARTH_MOON_DISTANCE / MANIM_REAL_SCALE * EARTH_MOON_DISTANCE_VISUALIZATION_FACTOR
RENDER_SUN_MARS_DISTANCE = SUN_MARS_DISTANCE / MANIM_REAL_SCALE 

#Celestial Sphere
CELESTIAL_SPHERE_RADIUS = RENDER_EARTH_RADIUS * 3
ELEMENTS_SCALE = CELESTIAL_SPHERE_RADIUS /2
RENDER_CELESTIAL_SPHERE_RADIUS = CELESTIAL_SPHERE_RADIUS

ASTRO_SIZE = ELEMENTS_SCALE*DEFAULT_DOT_RADIUS
LINE_SIZE = ELEMENTS_SCALE*25