
#SCALE
MANIM_REAL_SCALE = 1_000_000_000

#Basics
SUN_RADIUS = 696_340_000
EARTH_RADIUS = 6_378_000
MOON_RADIUS = 1_740_000

#Distances
SUN_EARTH_DISTANCE = 150_000_000_000
EARTH_MOON_DISTANCE = 384_400_000

#Visualization Factors
SUN_RADIUS_VISUALIZATION_FACTOR = 10000
EARTH_RADIUS_VISUALIZATION_FACTOR = 10000
MOON_RADIUS_VISUALIZATION_FACTOR = 10000

SUN_EARTH_DISTANCE_VISUALIZATION_FACTOR = 1
EARTH_MOON_DISTANCE_VISUALIZATION_FACTOR = 1

#Celestial Sphere
CELESTIAL_SPHERE_RADIUS = EARTH_RADIUS * 5

#Render Distance
RENDER_SUN_RADIUS = SUN_RADIUS / MANIM_REAL_SCALE * SUN_RADIUS_VISUALIZATION_FACTOR
RENDER_EARTH_RADIUS = EARTH_RADIUS / MANIM_REAL_SCALE * EARTH_RADIUS_VISUALIZATION_FACTOR
RENDER_MOON_RADIUS = MOON_RADIUS / MANIM_REAL_SCALE * MOON_RADIUS_VISUALIZATION_FACTOR
RENDER_SUN_EARTH_DISTANCE = SUN_EARTH_DISTANCE / MANIM_REAL_SCALE * SUN_EARTH_DISTANCE_VISUALIZATION_FACTOR
RENDER_EARTH_MOON_DISTANCE = EARTH_MOON_DISTANCE / MANIM_REAL_SCALE * EARTH_MOON_DISTANCE_VISUALIZATION_FACTOR
RENDER_CELESTIAL_SPHERE_RADIUS = CELESTIAL_SPHERE_RADIUS / MANIM_REAL_SCALE