from manimlib import DEFAULT_DOT_RADIUS
# SCALE (1_000_000_000)
MANIM_REAL_SCALE = 100_000_000*100

# Basics (radii in meters)
SUN_RADIUS = 696_340_000
MERCURY_RADIUS = 2_440_000
VENUS_RADIUS = 6_052_000
EARTH_RADIUS = 6_378_000
MOON_RADIUS = 1_740_000
MARS_RADIUS = 3_389_000
JUPITER_RADIUS = 69_911_000
SATURN_RADIUS = 58_232_000
URANUS_RADIUS = 25_362_000
NEPTUNE_RADIUS = 24_622_000

# Distances (mean orbital distance from the Sun, in meters)
SUN_MERCURY_DISTANCE = 57_910_000_000
SUN_VENUS_DISTANCE = 108_200_000_000
SUN_EARTH_DISTANCE = 150_000_000_000
EARTH_MOON_DISTANCE = 384_400_000
SUN_MARS_DISTANCE = 227_943_000_000
SUN_JUPITER_DISTANCE = 778_500_000_000
SUN_SATURN_DISTANCE = 1_433_000_000_000
SUN_URANUS_DISTANCE = 2_872_000_000_000
SUN_NEPTUNE_DISTANCE = 4_495_000_000_000

# Visualization Factors (adjust if you want to exaggerate small planets)
PLANETS_FACTOR = 100
SUN_RADIUS_VISUALIZATION_FACTOR = 1
MERCURY_RADIUS_VISUALIZATION_FACTOR = 1*PLANETS_FACTOR
VENUS_RADIUS_VISUALIZATION_FACTOR = 1*PLANETS_FACTOR
EARTH_RADIUS_VISUALIZATION_FACTOR = 1*PLANETS_FACTOR
MOON_RADIUS_VISUALIZATION_FACTOR = 1*PLANETS_FACTOR
MARS_RADIUS_VISUALIZATION_FACTOR = 1*PLANETS_FACTOR
JUPITER_RADIUS_VISUALIZATION_FACTOR = 1*PLANETS_FACTOR
SATURN_RADIUS_VISUALIZATION_FACTOR = 1*PLANETS_FACTOR
URANUS_RADIUS_VISUALIZATION_FACTOR = 1*PLANETS_FACTOR
NEPTUNE_RADIUS_VISUALIZATION_FACTOR = 1*PLANETS_FACTOR

SUN_EARTH_DISTANCE_VISUALIZATION_FACTOR = 1
EARTH_MOON_DISTANCE_VISUALIZATION_FACTOR = 1

# Render Sizes
RENDER_SUN_RADIUS = SUN_RADIUS / MANIM_REAL_SCALE * SUN_RADIUS_VISUALIZATION_FACTOR
RENDER_MERCURY_RADIUS = MERCURY_RADIUS / MANIM_REAL_SCALE * MERCURY_RADIUS_VISUALIZATION_FACTOR
RENDER_VENUS_RADIUS = VENUS_RADIUS / MANIM_REAL_SCALE * VENUS_RADIUS_VISUALIZATION_FACTOR
RENDER_EARTH_RADIUS = EARTH_RADIUS / MANIM_REAL_SCALE * EARTH_RADIUS_VISUALIZATION_FACTOR
RENDER_MOON_RADIUS = MOON_RADIUS / MANIM_REAL_SCALE * MOON_RADIUS_VISUALIZATION_FACTOR
RENDER_MARS_RADIUS = MARS_RADIUS / MANIM_REAL_SCALE * MARS_RADIUS_VISUALIZATION_FACTOR
RENDER_JUPITER_RADIUS = JUPITER_RADIUS / MANIM_REAL_SCALE * JUPITER_RADIUS_VISUALIZATION_FACTOR
RENDER_SATURN_RADIUS = SATURN_RADIUS / MANIM_REAL_SCALE * SATURN_RADIUS_VISUALIZATION_FACTOR
RENDER_URANUS_RADIUS = URANUS_RADIUS / MANIM_REAL_SCALE * URANUS_RADIUS_VISUALIZATION_FACTOR
RENDER_NEPTUNE_RADIUS = NEPTUNE_RADIUS / MANIM_REAL_SCALE * NEPTUNE_RADIUS_VISUALIZATION_FACTOR

# Render Distances
RENDER_SUN_MERCURY_DISTANCE = SUN_MERCURY_DISTANCE / MANIM_REAL_SCALE
RENDER_SUN_VENUS_DISTANCE = SUN_VENUS_DISTANCE / MANIM_REAL_SCALE
RENDER_SUN_EARTH_DISTANCE = SUN_EARTH_DISTANCE / MANIM_REAL_SCALE * SUN_EARTH_DISTANCE_VISUALIZATION_FACTOR
RENDER_EARTH_MOON_DISTANCE = EARTH_MOON_DISTANCE / MANIM_REAL_SCALE * EARTH_MOON_DISTANCE_VISUALIZATION_FACTOR
RENDER_SUN_MARS_DISTANCE = SUN_MARS_DISTANCE / MANIM_REAL_SCALE
RENDER_SUN_JUPITER_DISTANCE = SUN_JUPITER_DISTANCE / MANIM_REAL_SCALE
RENDER_SUN_SATURN_DISTANCE = SUN_SATURN_DISTANCE / MANIM_REAL_SCALE
RENDER_SUN_URANUS_DISTANCE = SUN_URANUS_DISTANCE / MANIM_REAL_SCALE
RENDER_SUN_NEPTUNE_DISTANCE = SUN_NEPTUNE_DISTANCE / MANIM_REAL_SCALE

# Celestial Sphere
CELESTIAL_SPHERE_RADIUS = RENDER_EARTH_RADIUS * 3
RENDER_CELESTIAL_SPHERE_RADIUS = CELESTIAL_SPHERE_RADIUS
ELEMENTS_SCALE = RENDER_CELESTIAL_SPHERE_RADIUS / 2

ASTRO_SIZE = ELEMENTS_SCALE * DEFAULT_DOT_RADIUS
LINE_SIZE = 20*ELEMENTS_SCALE 

#More
OBLIQUIDADE = 23.5 
MERCURY_OBLIQUITY = -0.03
VENUS_OBLIQUITY = 177.4
EARTH_OBLIQUITY = 23.4
MARS_OBLIQUITY = -25.2
JUPITER_OBLIQUITY = 3.1
SATURN_OBLIQUITY = -26.7
URANUS_OBLIQUITY = 97.8
NEPTUNE_OBLIQUITY = 28.3
